# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrderWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderWidget(object):
    def setupUi(self, OrderWidget):
        OrderWidget.setObjectName("OrderWidget")
        OrderWidget.setEnabled(True)
        OrderWidget.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OrderWidget.sizePolicy().hasHeightForWidth())
        OrderWidget.setSizePolicy(sizePolicy)
        OrderWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        OrderWidget.setAutoFillBackground(True)
        self.tip_label = QtWidgets.QLabel(OrderWidget)
        self.tip_label.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tip_label.setFont(font)
        self.tip_label.setAutoFillBackground(False)
        self.tip_label.setObjectName("tip_label")
        self.tip_label2 = QtWidgets.QLabel(OrderWidget)
        self.tip_label2.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tip_label2.setFont(font)
        self.tip_label2.setObjectName("tip_label2")
        self.pushButtonClose = QtWidgets.QPushButton(OrderWidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(440, 0, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClose.sizePolicy().hasHeightForWidth())
        self.pushButtonClose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.pushButtonID = QtWidgets.QPushButton(OrderWidget)
        self.pushButtonID.setGeometry(QtCore.QRect(30, 80, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonID.setFont(font)
        self.pushButtonID.setAutoFillBackground(True)
        self.pushButtonID.setObjectName("pushButtonID")
        self.pushButtonPhone = QtWidgets.QPushButton(OrderWidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(180, 80, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPhone.setFont(font)
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonOrder = QtWidgets.QPushButton(OrderWidget)
        self.pushButtonOrder.setGeometry(QtCore.QRect(330, 80, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOrder.setFont(font)
        self.pushButtonOrder.setObjectName("pushButtonOrder")
        self.id_type_lineEdit = QtWidgets.QLineEdit(OrderWidget)
        self.id_type_lineEdit.setEnabled(True)
        self.id_type_lineEdit.setGeometry(QtCore.QRect(20, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_type_lineEdit.setFont(font)
        self.id_type_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.id_type_lineEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.id_type_lineEdit.setText("")
        self.id_type_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.id_type_lineEdit.setObjectName("id_type_lineEdit")
        self.id_type_label = QtWidgets.QLabel(OrderWidget)
        self.id_type_label.setGeometry(QtCore.QRect(50, 180, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_type_label.setFont(font)
        self.id_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_type_label.setObjectName("id_type_label")
        self.id_lineEdit = QtWidgets.QLineEdit(OrderWidget)
        self.id_lineEdit.setEnabled(True)
        self.id_lineEdit.setGeometry(QtCore.QRect(150, 150, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_lineEdit.setFont(font)
        self.id_lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.id_lineEdit.setAutoFillBackground(False)
        self.id_lineEdit.setText("")
        self.id_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.id_label = QtWidgets.QLabel(OrderWidget)
        self.id_label.setGeometry(QtCore.QRect(300, 180, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_label.setFont(font)
        self.id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label.setObjectName("id_label")
        self.layoutWidget = QtWidgets.QWidget(OrderWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 230, 471, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        self.pushButton1.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout.addWidget(self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        self.pushButton2.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayout.addWidget(self.pushButton2)
        self.pushButton3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton3.sizePolicy().hasHeightForWidth())
        self.pushButton3.setSizePolicy(sizePolicy)
        self.pushButton3.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton3.setFont(font)
        self.pushButton3.setObjectName("pushButton3")
        self.horizontalLayout.addWidget(self.pushButton3)
        self.pushButton4 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton4.sizePolicy().hasHeightForWidth())
        self.pushButton4.setSizePolicy(sizePolicy)
        self.pushButton4.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton4.setFont(font)
        self.pushButton4.setObjectName("pushButton4")
        self.horizontalLayout.addWidget(self.pushButton4)
        self.pushButton5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton5.sizePolicy().hasHeightForWidth())
        self.pushButton5.setSizePolicy(sizePolicy)
        self.pushButton5.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton5.setFont(font)
        self.pushButton5.setObjectName("pushButton5")
        self.horizontalLayout.addWidget(self.pushButton5)
        self.pushButton6 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton6.sizePolicy().hasHeightForWidth())
        self.pushButton6.setSizePolicy(sizePolicy)
        self.pushButton6.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton6.setFont(font)
        self.pushButton6.setObjectName("pushButton6")
        self.horizontalLayout.addWidget(self.pushButton6)
        self.pushButton7 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton7.sizePolicy().hasHeightForWidth())
        self.pushButton7.setSizePolicy(sizePolicy)
        self.pushButton7.setMinimumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton7.setFont(font)
        self.pushButton7.setObjectName("pushButton7")
        self.horizontalLayout.addWidget(self.pushButton7)
        self.pushButtonConfirm = QtWidgets.QPushButton(OrderWidget)
        self.pushButtonConfirm.setGeometry(QtCore.QRect(380, 360, 120, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConfirm.sizePolicy().hasHeightForWidth())
        self.pushButtonConfirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonConfirm.setFont(font)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.layoutWidget1 = QtWidgets.QWidget(OrderWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 280, 401, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton8 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton8.sizePolicy().hasHeightForWidth())
        self.pushButton8.setSizePolicy(sizePolicy)
        self.pushButton8.setMinimumSize(QtCore.QSize(50, 41))
        self.pushButton8.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton8.setFont(font)
        self.pushButton8.setObjectName("pushButton8")
        self.horizontalLayout_2.addWidget(self.pushButton8)
        self.pushButton9 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton9.sizePolicy().hasHeightForWidth())
        self.pushButton9.setSizePolicy(sizePolicy)
        self.pushButton9.setMinimumSize(QtCore.QSize(50, 41))
        self.pushButton9.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton9.setFont(font)
        self.pushButton9.setObjectName("pushButton9")
        self.horizontalLayout_2.addWidget(self.pushButton9)
        self.pushButton0 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton0.sizePolicy().hasHeightForWidth())
        self.pushButton0.setSizePolicy(sizePolicy)
        self.pushButton0.setMinimumSize(QtCore.QSize(50, 41))
        self.pushButton0.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton0.setFont(font)
        self.pushButton0.setObjectName("pushButton0")
        self.horizontalLayout_2.addWidget(self.pushButton0)
        self.pushButtonX = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonX.sizePolicy().hasHeightForWidth())
        self.pushButtonX.setSizePolicy(sizePolicy)
        self.pushButtonX.setMinimumSize(QtCore.QSize(50, 41))
        self.pushButtonX.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonX.setFont(font)
        self.pushButtonX.setObjectName("pushButtonX")
        self.horizontalLayout_2.addWidget(self.pushButtonX)
        self.pushButtonBack = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBack.sizePolicy().hasHeightForWidth())
        self.pushButtonBack.setSizePolicy(sizePolicy)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButtonBack.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_2.addWidget(self.pushButtonBack)
        self.pushButtonClear = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClear.sizePolicy().hasHeightForWidth())
        self.pushButtonClear.setSizePolicy(sizePolicy)
        self.pushButtonClear.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButtonClear.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout_2.addWidget(self.pushButtonClear)

        self.retranslateUi(OrderWidget)
        QtCore.QMetaObject.connectSlotsByName(OrderWidget)

    def retranslateUi(self, OrderWidget):
        _translate = QtCore.QCoreApplication.translate
        OrderWidget.setWindowTitle(_translate("OrderWidget", "Form"))
        self.tip_label.setText(_translate("OrderWidget", "请选择你的预约条件"))
        self.tip_label2.setText(_translate("OrderWidget", "并输入你的号码"))
        self.pushButtonClose.setText(_translate("OrderWidget", "关闭"))
        self.pushButtonID.setText(_translate("OrderWidget", "身份证"))
        self.pushButtonPhone.setText(_translate("OrderWidget", "手机号码"))
        self.pushButtonOrder.setText(_translate("OrderWidget", "预约码"))
        self.id_type_label.setText(_translate("OrderWidget", "类型"))
        self.id_label.setText(_translate("OrderWidget", "号码"))
        self.pushButton1.setText(_translate("OrderWidget", "1"))
        self.pushButton2.setText(_translate("OrderWidget", "2"))
        self.pushButton3.setText(_translate("OrderWidget", "3"))
        self.pushButton4.setText(_translate("OrderWidget", "4"))
        self.pushButton5.setText(_translate("OrderWidget", "5"))
        self.pushButton6.setText(_translate("OrderWidget", "6"))
        self.pushButton7.setText(_translate("OrderWidget", "7"))
        self.pushButtonConfirm.setText(_translate("OrderWidget", "确定"))
        self.pushButton8.setText(_translate("OrderWidget", "8"))
        self.pushButton9.setText(_translate("OrderWidget", "9"))
        self.pushButton0.setText(_translate("OrderWidget", "0"))
        self.pushButtonX.setText(_translate("OrderWidget", "X"))
        self.pushButtonBack.setText(_translate("OrderWidget", "回退"))
        self.pushButtonClear.setText(_translate("OrderWidget", "清空"))

